# Navigation Links

[[main]]
  name = "Home"
  url = "#intro"
  weight = 10

[[main]]
  name = "News"
  url = "#posts"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Math"
  url = "/post/statistics/"
  weight =40

[[main]]
  name = "Biology"
  url = "/post/biology/"
  weight = 50

[[main]]
  name = "Sport"
  url = "/post/sport/"
  weight = 60

[[main]]
  name = "About"
  url = "#about"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80
