# Navigation Links

[[main]]
  name = "Intro"
  url = "#intro"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "About"
  url = "#about"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50
