---
title: "Polycomb and Trithorax group proteins"
author: "Mark Boltengagen"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
draft: false
math: false
tags: ["Epigenetics", "PcG", "Trx"]
categories: ["Epigenetics"]
bibliography: [bib.bib]
output:
  blogdown::html_page:
    toc: true
---

## Polycomb group PcG proteins
**Polycomb group** (PcG) proteins generally maintain gene repression, whereas **Trithorax group** (TrxG) proteins maintain the active gene expression.  

PcG and TrxG proteins were initially isolated in _Drosophila_ as factors involved in maintaining the expression patterns of HOX genes, which encode transcription factors that are important determinants of patterning during embryonic development.  

In mammals, PRCs are targeted to a subset of CpG islands (CGIs) at the promoters of developmental genes and prevent unscheduled cellular differentiation.  

In _drosophila_ PcG proteins form _Polycomb repressive complex 1_ (**PRC1**), _Polycomb repressive complex 2_ (**PRC2**) and _Pleiohomeotic_ (Pho) _repressive complex_ (**PhoRC**). PRC2 and PRC1 are recruited to chromatin by PhoRC which directly binds _polycomb response elements_ (**PREs**).  

## PRC1
PRC1 ubiquitinylates histone H2AK119 (H2AK118 in Drosophila) and alter chromatin structure whereas PRC2 trimethylates histone H3K27.  

PRC1 is composed of the core components **Polycomb** (Pc), **Polyhomeotic** (Ph), **Posterior sex combs** (Psc) and **Sex combs extra**.  

Pc can bind the H3K27me3 that facilitate anchoring the complex to chromatin.  

Psc and Sce form a heterodimer, which enhances the E3 ubiquitin ligase activity of the complex. This activity is provided by the Sce subunit of 

PRC1, which monoubiquitylates H2AK118 (K119 in mammals). This ubiquitylation event is thought to restrict RNA polymerase II (Pol II) elongation, but was also shown to recruit PRC2 members.  

Ph subunit is able to bind itself that promotes spreading of PRC1 complex.  

## PRC2
PRC2 core complex is composed of **Enhancer of zeste** E(z), **Suppressor of zeste 12** Su(z)12, **Extra sex combs** (Esc) and **p55** (Nurf55 or Caf1).  

E(z) methylate H3K27.

Esc bind H3K27me3 and facilitates multimerization of complex.

PRC1-mediated events are also thought to compact chromatin to limit the access of activating factors and the Psc subunit in particular has been linked to this function.

p55 is present in a number of chromatin remodeling complexes and interacts with Su(z)12, H3 and H4. The loss of loss of p55 appears to have little consequence on PRC2 activity.  

## Pho-complex
The first complex, referred to as Pho repressive complex (PhoRC), is composed of Pho and Sfmbt. A second Pho-containing complex has also been described (Pho-INO80) that, in addition to Pho, contains the INO80 nucleosome remodeling complex (Klymenko, 2006).
Pho binds DNA in a sequence-specific manner and help to recruit PcG complexes to their response elements (Grossniklaus and Paro, 2014).   

## Mechanisms of inactivation of gene expression
After the initial recruitment of PRC2 and PRC1 by Pho protein, Enhancer of zeste **E(z)**, a member of PRC2, methylate H3 histone (H3K27me3) at both PREs and along the gene body. This modification is then recognized by Pc, a member of PRC1, which, in turn, ubiquitylates H2A119 via Sex combs extra (**Sce**), another PRC1 member, and stabilizes PRC2. The accumulation of PRC1 and PRC2 within gene bodies results in the compaction of local nucleosomes and the further silencing of the inactive genes.

## TrxG complex components

TrxG include the COMPASS, COMPASS-like, TAC1 and ASH1 complexes, and SET domain HMTs.  

Common subunits for COMPASS and COMPASS-like complexes include Ash2, Dpy30 (Dpy-30L1), Hcf1 (Hcf), Rbbp5 and Wds. 

## PcG/TrxG response elements
In Drosophila, the genomic nucleation sites of PcG- and TrxG-mediated epigenetic memory have been referred to as PcG/TrxG response elements (PRE/TREs).  

## Nuclear architecture
Nuclear architecture by PRC1 complex is disscussed in the recent review [@illingworth_chromatin_2019]

## Open questions
1. Although some PRE/TRE-like elements have been identified, it is unclear if all of the properties of the Drosophila PRE/TRE (e.g. epigenetic memory) are maintained in the mammalian system.  

2. How PcG and TrxG proteins are recruited to these elements?  
We currently lack a clear understanding of the hierarchical recruitment of PcG and TrxG proteins to PRE/TREs, and elucidating these recruitment mechanisms is thus an area of active research.  

3. What determines the active (TRE) versus repressed (PRE) state?

4. What factors d which PRC1 targets will physically interact?

5. What is the impact of stoichiometry of PRC1 subunits during development?

This page summarizes several recent reviews [@geisler_trithorax_2015] to aggregate information in this actively studied area of research.

## Glossary
**PRC1** - Polycomb Repressive Complex 1  
**PRC2** - Polycomb Repressive Complex 2  
**Pho** - Pleiohomeotic  
**PhoRC** - Pleiohomeotic Repressive Complex  
**PREs** - Polycomb Response Elements  
**Psc** - Posterior Sex Combs  
**E(z)** - Enhancer of zeste  
**Su(z)12** - Suppressor of zeste 12  
**Esc** - Extra sex combs

## Cited literature
