---
title: "Neuralnet R"
author: "Mark Goldberg"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
draft: false
math: true
tags: ["R", "Statistics", "Classification", "Neural Network"]
categories: ["Statistics"]
#bibliography: [bib.bib]
output:
  #blogdown::html_page:
  toc: true
summary: "Examples of Neural Network classification using Neuralnet R package."
---

Using of `neuralnet` R package to tran Neural Network for classification.  
```{r}
library(neuralnet)
library(datasets)

# data
df <- datasets::iris
head(df)

# split data
train.ratio = 0.9
n = nrow(df)

train.id <- sample(n, size = n*train.ratio)
train <- df[train.id,]
test <- df[-train.id,]
```
## Binary classification
```{r}
nn <- neuralnet(Species == "setosa" ~ Petal.Length + Petal.Width, train, linear.output = FALSE)

# Predict for test data
pred <- predict(nn, test)
# Confusion matrix
t <- table(test$Species == "setosa", pred[, 1] > 0.5)
t
# plot NN
plot(nn)

# Confusion matrix using caret
library(caret)
caret::confusionMatrix(t)
```

## Multiclass classification
```{r}
nn <- neuralnet((Species == "setosa") + (Species == "versicolor") + (Species == "virginica") 
                ~ Petal.Length + Petal.Width, train, linear.output = FALSE)

# Predict for test data
pred <- predict(nn, test)
table(test$Species, apply(pred, 1, which.max))

# Plot NN
plot(nn)

# Confusion matrix using 'caret'
caret::confusionMatrix(t)
```

## Neuralnet with 2 hidden neurons
```{r}
library(datasets)
library(neuralnet)
library(caret)

# data
df <- datasets::iris
head(df)

# split data
train.ratio = 0.9
n = nrow(df)

train.id <- sample(n, size = n*train.ratio)
train <- df[train.id,]
test <- df[-train.id,]

nn <- neuralnet(Species == "versicolor" ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, train, hidden = 2, linear.output = FALSE)

# Predict for test data
pred <- predict(nn, test)
# Confusion matrix
t <- table(test$Species == "versicolor", pred[, 1] > 0.5)
# Confusion matrix
caret::confusionMatrix(t)

# plot NN
plot(nn, rep='best')

# compair predicted and actual values
test$predicted <- ifelse(pred>0.5, 1, 0)
test
```

## Bibliography
